### ISSUE TITLE
Just a friendly share on the workflow file

### ISSUE THREAD

**Issue by maggie44** [justinthelaw/isolated-docker-gpu#2]
Hey,

I had a similar issue to you with my GitHub deploy workflow that you had logged on the Docker repo. I found your workflow in this repo helpful and got me on my way. 

I discovered through that for private images I had to reverse the order of the login and the metadata steps:

https://github.com/justinthelaw/gpu-support-test/blob/baee593a78b837b30a9b31a0eb263289ff0a5c82/.github/workflows/build-and-push-image.yaml#L93-L112

I assume this isn't an issue for you, but dropping a quick message here to potentially save you some hassle later.

**Comment by justinthelaw** [comment]
Oh that's an awesome find! I am glad you found it useful. If you want to or can, I can merge a PR with your fix?
